name: Humble Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
        ROS_REPO: [main, testing]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: kinematics_interface-not-released.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: humble
  binary_clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      # job for building only, no tests -> one distro is enough
      ros_distro: humble
      ros_repo: testing
      upstream_workspace: kinematics_interface-not-released.humble.repos
      ref_for_scheduled_build: humble
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
