name: Debian Humble Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '33 2 * * *'


jobs:
  debian_source_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-debian-build.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      upstream_workspace: kinematics_interface.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
