name: Debian Humble Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '33 2 * * *'


jobs:
  humble_debian:
    name: Humble debian build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    container: ghcr.io/ros-controls/ros:humble-debian
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/kinematics_interface
      - name: Build and test
        shell: bash
        run: |
          source /opt/ros2_ws/install/setup.bash
          vcs import src < src/kinematics_interface/kinematics_interface.${{ env.ROS_DISTRO }}.repos
          colcon build --packages-up-to kinematics_interface kinematics_interface_kdl
          colcon test --packages-select kinematics_interface kinematics_interface_kdl
          colcon test-result --verbose
