name: Humble RHEL Binary Build
on:
  workflow_dispatch:
    branches:
      - master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  humble_rhel_binary:
    name: Humble RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    container: ghcr.io/ros-controls/ros:humble-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/kinematics_interface
      - run: |
          rosdep update
          rosdep install -iy --from-path src/kinematics_interface
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
