name: RHEL Humble Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '42 4 * * *'

jobs:
  humble_rhel_binary:
    name: Humble RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    container: ghcr.io/ros-controls/ros:humble-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/kinematics_interface
          ref: ${{ github.event_name == 'schedule' && 'humble' || '' }}
      - name: Install dependencies
        run: |
          rosdep update
          rosdep install -iyr --from-path src/kinematics_interface || true
      - name: Build and test
        run: |
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          source /opt/ros2_ws/install/setup.bash
          colcon build
          colcon test
          colcon test-result --verbose
