name: Iron Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: iron
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: kinematics_interface.iron.repos
      ref_for_scheduled_build: master
