name: Jazzy - Semi-Binary Build
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on humble branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  semi_binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      upstream_workspace: kinematics_interface.jazzy.repos
      ref_for_scheduled_build: jazzy
  semi_binary_clang:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      # job for building only, no tests -> one distro is enough
      ros_distro: jazzy
      ros_repo: testing
      upstream_workspace: kinematics_interface.jazzy.repos
      ref_for_scheduled_build: jazzy
      additional_debs: clang
      c_compiler: clang
      cxx_compiler: clang++
      not_test_build: true
