name: Jazzy - Rolling Downstream Build
# description: 'Build & test downstream packages from source.'
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-downstream:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      ref_for_scheduled_build: master
      not_test_build: true
      upstream_workspace: kinematics_interface.jazzy.repos
      # we test the downstream packages, which are part of our organization
      downstream_workspace: ros_controls.jazzy.repos
      not_test_downstream: false
