name: Jazzy - Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - jazzy
  push:
    branches:
      - jazzy
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on humble branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  binary:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: jazzy
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: kinematics_interface-not-released.jazzy.repos
      ref_for_scheduled_build: jazzy
