name: Rolling Binary Build
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    strategy:
      matrix:
        ROS_REPO: [main, testing]
    with:
      ros_distro: rolling
      ros_repo: ${{ matrix.ROS_REPO }}
      upstream_workspace: kinematics_interface-not-released.rolling.repos
      ref_for_scheduled_build: master
