name: RHEL Semi-Binary Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '42 4 * * *'


jobs:
  rhel_semi_binary_build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rhel-binary-build.yml@master
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, jazzy, iron]
    with:
      ros_distro: ${{ matrix.ROS_DISTRO }}
      upstream_workspace: kinematics_interface.${{ matrix.ROS_DISTRO }}.repos
      ref_for_scheduled_build: master
